[package]
name = "psc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.18"
rand_core = "0.6.4"
subtle = "2.5.0"
zeroize = "1.7.0"
